const K="taskflow_tasks",U="taskflow_user";
const tasks=()=>JSON.parse(localStorage.getItem(K)||"[]");
const setTasks=x=>localStorage.setItem(K,JSON.stringify(x));
const user=()=>JSON.parse(localStorage.getItem(U)||"null");
function initials(n){return (n||"U").trim().split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}
function init(){let u=user();if(document.getElementById("user")){document.getElementById("user").textContent=u?.name||"there";document.getElementById("avatar").textContent=initials(u?.name)}dashboard();render();loadProfile()}
function login(){let n=document.getElementById("name").value.trim(),e=document.getElementById("email").value.trim();if(!n||!e)return alert("Please enter your name and email.");localStorage.setItem(U,JSON.stringify({name:n,email:e}));location.href="home.html"}
function demo(){localStorage.setItem(U,JSON.stringify({name:"Owais",email:"demo@taskflow.app"}));if(!tasks().length)setTasks([{id:1,title:"Complete DBMS assignment",desc:"Finish ER diagrams and key concepts.",priority:"high",due:"",done:false},{id:2,title:"Prepare presentation speech",desc:"Practice the college presentation.",priority:"medium",due:"",done:false},{id:3,title:"Review Python project",desc:"Check the Advanced To-Do List code.",priority:"low",due:"",done:true}]);location.href="home.html"}
function logout(){localStorage.removeItem(U);location.href="index.html"}
function dashboard(){let el=document.getElementById("total");if(!el)return;let a=tasks(),done=a.filter(x=>x.done).length,p=a.length-done,h=a.filter(x=>x.priority==="high"&&!x.done).length,pc=a.length?Math.round(done/a.length*100):0;document.getElementById("total").textContent=a.length;document.getElementById("completed").textContent=done;document.getElementById("pending").textContent=p;document.getElementById("high").textContent=h;document.getElementById("progress").textContent=pc+"%";document.getElementById("progressbar").style.width=pc+"%";let r=document.getElementById("recent");r.innerHTML=a.slice().reverse().slice(0,5).map(x=>`<div class="taskrow"><div class="check ${x.done?"done":""}" onclick="toggle(${x.id})">${x.done?"✓":""}</div><div class="taskname ${x.done?"done":""}">${esc(x.title)}</div><span class="priority ${x.priority}">${x.priority}</span></div>`).join("")||'<div class="empty">No tasks yet. Add your first task.</div>'}
function render(){let list=document.getElementById("list");if(!list)return;let q=(document.getElementById("search")?.value||"").toLowerCase(),st=document.getElementById("status")?.value||"all",pr=document.getElementById("filterPriority")?.value||"all";let a=tasks().filter(x=>(!q||x.title.toLowerCase().includes(q)||x.desc.toLowerCase().includes(q))&&(st==="all"||(st==="done"&&x.done)||(st==="pending"&&!x.done))&&(pr==="all"||x.priority===pr));list.innerHTML=a.map(x=>`<article class="taskcard"><h3>${esc(x.title)}</h3><p>${esc(x.desc||"No description")}</p><div class="taskmeta"><span class="priority ${x.priority}">${x.priority}</span>${x.due?`<span class="pill">Due ${x.due}</span>`:""}<span class="pill">${x.done?"Completed":"Pending"}</span></div><div class="actions"><button class="btn" onclick="toggle(${x.id})">${x.done?"Reopen":"Complete"}</button><button class="btn secondary" onclick="editTask(${x.id})">Edit</button><button class="btn danger" onclick="del(${x.id})">Delete</button></div></article>`).join("")||'<div class="card empty">No matching tasks.</div>'}
function toggle(id){let a=tasks();let x=a.find(x=>x.id===id);if(x)x.done=!x.done;setTasks(a);dashboard();render()}
function del(id){if(confirm("Delete this task?")){setTasks(tasks().filter(x=>x.id!==id));dashboard();render()}}
function openModal(id=null){document.getElementById("modal").classList.add("show");document.getElementById("edit").value=id||"";if(id){let x=tasks().find(x=>x.id===id);document.getElementById("modalTitle").textContent="Edit Task";document.getElementById("title").value=x.title;document.getElementById("desc").value=x.desc;document.getElementById("priority").value=x.priority;document.getElementById("due").value=x.due||""}else{document.getElementById("modalTitle").textContent="Add Task";document.getElementById("title").value="";document.getElementById("desc").value="";document.getElementById("priority").value="medium";document.getElementById("due").value=""}}
function closeModal(){document.getElementById("modal").classList.remove("show")}
function editTask(id){openModal(id)}
function save(){let title=document.getElementById("title").value.trim();if(!title)return alert("Enter a task title.");let id=Number(document.getElementById("edit").value),a=tasks(),data={title,desc:document.getElementById("desc").value.trim(),priority:document.getElementById("priority").value,due:document.getElementById("due").value};if(id){let x=a.find(x=>x.id===id);Object.assign(x,data)}else{a.push({id:Date.now(),...data,done:false})}setTasks(a);closeModal();dashboard();render()}
function loadProfile(){let u=user();if(document.getElementById("pname")){document.getElementById("pname").textContent=u?.name||"User";document.getElementById("pemail").textContent=u?.email||"email@example.com";document.getElementById("bigavatar").textContent=initials(u?.name)}}
function clearTasks(){if(confirm("Delete all tasks?")){setTasks([]);dashboard();render()}}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.addEventListener("DOMContentLoaded",init);
